In [2]:
import numpy as np

# Create Sample Dataset
# create a dataset with 10 samples and 2 features

X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0],
    [2.3, 2.7],
    [2.0, 1.6],
    [1.0, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
])

print("Original Data:")
print(X)

Original Data:
[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]


In [ ]:
rows = len(X)
cols = len(X[0])
mean = []
for j in range(cols):
    column_sum = 0
    for i in range(rows):
        column_sum += X[i][j]
    mean.append(column_sum / rows)

print("Mean Vector:")
print(mean)

centered_data = []
for i in range(rows):
    centered_row = []
    for j in range(cols):
        centered_row.append(X[i][j] - mean[j])
    centered_data.append(centered_row)

print("Centered Data:")
print(centered_data)


cov_matrix = []

for i in range(cols):
    row = []

    for j in range(cols):
        cov = 0

        for k in range(rows):
            cov += centered_data[k][i] * centered_data[k][j]

        cov = cov / (rows - 1)
        row.append(cov)

    cov_matrix.append(row)

print("Covariance Matrix:")
for row in cov_matrix:
    print(row)



Mean Vector:
[np.float64(1.81), np.float64(1.9099999999999997)]
Centered Data:
[[np.float64(0.69), np.float64(0.4900000000000002)], [np.float64(-1.31), np.float64(-1.2099999999999997)], [np.float64(0.3900000000000001), np.float64(0.9900000000000002)], [np.float64(0.08999999999999986), np.float64(0.2900000000000005)], [np.float64(1.29), np.float64(1.0900000000000003)], [np.float64(0.48999999999999977), np.float64(0.7900000000000005)], [np.float64(0.18999999999999995), np.float64(-0.3099999999999996)], [np.float64(-0.81), np.float64(-0.8099999999999996)], [np.float64(-0.31000000000000005), np.float64(-0.3099999999999996)], [np.float64(-0.71), np.float64(-1.0099999999999998)]]
Covariance Matrix:
[np.float64(0.6165555555555556), np.float64(0.6154444444444445)]
[np.float64(0.6154444444444445), np.float64(0.7165555555555556)]


In [3]:
mean = np.mean(X, axis=0)

print("Mean Vector:")
print(mean)

Mean Vector:
[1.81 1.91]


In [4]:
X_centered = X - mean

print("Centered Data:")
print(X_centered)

Centered Data:
[[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]]


In [5]:
cov_matrix = np.cov(X_centered.T)

print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


In [6]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[0.0490834  1.28402771]
Eigenvectors:
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [7]:
sorted_index = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[sorted_index]
eigenvectors = eigenvectors[:, sorted_index]

print("Sorted Eigenvalues:")
print(eigenvalues)

print("Sorted Eigenvectors:")
print(eigenvectors)

Sorted Eigenvalues:
[1.28402771 0.0490834 ]
Sorted Eigenvectors:
[[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]


In [8]:
k = 1

principal_components = eigenvectors[:, :k]

print("Principal Component:")
print(principal_components)

Principal Component:
[[-0.6778734 ]
 [-0.73517866]]


In [11]:
X_pca = X_centered @ principal_components

print("Data after PCA:")
print(X_pca)

Data after PCA:
[[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]


In [9]:
from sklearn.decomposition import PCA

pca = PCA(n_components=k)
X_pca = pca.fit_transform(X)

print("PCA Result:")
print(X_pca)

PCA Result:
[[ 0.82797019]
 [-1.77758033]
 [ 0.99219749]
 [ 0.27421042]
 [ 1.67580142]
 [ 0.9129491 ]
 [-0.09910944]
 [-1.14457216]
 [-0.43804614]
 [-1.22382056]]


In [10]:
explained_variance = eigenvalues / np.sum(eigenvalues)

print("Explained variance ratio:")
print(explained_variance)

print("Percentage:")
print(explained_variance * 100)

Explained variance ratio:
[0.96318131 0.03681869]
Percentage:
[96.31813143  3.68186857]
