In [1]:
import torch
import random


In [ ]:
RANDOM_SEED = 45
torch.manual_seed(seed=RANDOM_SEED)
a=torch.rand(3,4)

# Have to reset the seed every time a new rand() is called 
torch.manual_seed(seed=RANDOM_SEED)
b=torch.rand(3,4)
print(a)
print(b)
a==b

tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [8]:
torch.cuda.is_available()

False