In [5]:
import torch

x=torch.zeros(3,4)
rand=torch.rand(2,3)
# 3*4 matrix
print(x)
print(x.dtype)
print(rand)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[0.1415, 0.4600, 0.6977],
        [0.8845, 0.6019, 0.5673]])


In [10]:
ones=torch.ones(3,4)
twos=ones*2
threes=ones*3
summation=ones+twos+threes
print(summation)


tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [15]:
r=torch.rand(3,3)-0.5**2
print("A random Matrix:")
print(r)

print("\n Absolute value r")
print(torch.abs(r))

print("\n Determninant of r")
print(torch.det(r))

print("\n SIngular value decomposition r")
print(torch.svd(r))

print("\n Avarage and standart deviation of value r")
print(torch.std_mean(r))


A random Matrix:
tensor([[ 0.7359, -0.0574, -0.0867],
        [ 0.0874, -0.1143,  0.6338],
        [ 0.6865,  0.5546,  0.1600]])

 Absolute value r
tensor([[0.7359, 0.0574, 0.0867],
        [0.0874, 0.1143, 0.6338],
        [0.6865, 0.5546, 0.1600]])

 Determninant of r
tensor(-0.3073)

 SIngular value decomposition r
torch.return_types.svd(
U=tensor([[-0.5976, -0.2348,  0.7666],
        [-0.1175,  0.9715,  0.2060],
        [-0.7931,  0.0330, -0.6082]]),
S=tensor([1.0794, 0.6495, 0.4383]),
V=tensor([[-0.9213, -0.1004,  0.3756],
        [-0.3633, -0.1220, -0.9237],
        [-0.1386,  0.9874, -0.0759]]))

 Avarage and standart deviation of value r
(tensor(0.3585), tensor(0.2889))
